# Generated by Django 4.0.3 on 2024-07-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='createed_at',
            new_name='created_at',
        ),
    ]
